### ISSUE TITLE
Options set on form label should be applied to `fields_for` as well

### ISSUE THREAD

**Issue by protaskz-in** [shivam091/rails_bootstrap_form#10]
Hello @shivam091 ,

I was working with forms having nested attributes and I found that bootstrap options set on form label don't get applied to `fields_for`.

```html
<%= bootstrap_form_for @user, bootstrap_form: {skip_label: true} do |form| %>
  ...
  <%= form.fields_for :address, include_id: false do |address_form| %>
    ... 
    ...
  <% end %>
<% end %>
```
But still labels are shown in fields added under `fields_for` block.

**Comment by shivam091** [comment]
Hi,

Thanks for reporting this issue. We will soon work on this.

**Comment by shivam091** [comment]
This is fixed.
