### ISSUE TITLE
Wrapper class is overwriting existing field wrapper classes

### ISSUE THREAD

**Issue by protaskz-in** [shivam091/rails_bootstrap_form#29]
Hi,

While integrating this library, I come across the one suggestion that existing wrapper classes should not be overwritten by `wrapper_options: {class: "..."}`

Due to this overwrite, we need to again mention wrapper class for that field.

Thanks.

**Comment by shivam091** [comment]
Hello,

Here, I am going to provide two ways to customize CSS class of the wrapper.

1. Default wrapper class will be replaced by `wrapper[:class]`
2. To add additional CSS class to the wrapper, new option `additional_wrapper_class` will be provided which will append the class to default wrapper classes
