### ISSUE TITLE
`required` class should not be applied

### ISSUE THREAD

**Issue by protaskz-in** [shivam091/rails_bootstrap_form#34]
Hi.

`required` class should not be applied for control labels of `collection_check_boxes` and `collection_radio_buttons` helpers. At present, this is happening but I don't think, it is need as field label itself has `required` class.

Thanks.

**Comment by shivam091** [comment]
Thank you for reporting this.

**Comment by shivam091** [comment]
Hello @protaskz-in 

This will be fixed in next release `0.9.2`
